* big function rename to <tool>::<file>::<function> to make it easier to read hopefully

diff --git a/test/71-guess/run-test b/test/71-guess/run-test
--- a/test/71-guess/run-test
+++ b/test/71-guess/run-test
@@ -1,6 +1,13 @@
-#! /usr/bin/env bash
+#! /bin/sh
 
-[ "${TRACE}" = 'YES' ] && set -x
+[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"
+
+###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
+MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
+export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
+. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
+. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
+###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
 
 
 run_mulle_domain()
@@ -31,6 +38,8 @@ run_test1()
    then
       fail "empty guess unexpectedly succeded"
    fi
+   log_info "Failed as expected"
+
    log_verbose "----- #1 PASSED -----"
 
    result="`run_mulle_domain nameguess /name`"
@@ -133,10 +142,6 @@ main()
 
 init()
 {
-   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1
-
-   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
-
    MULLE_DOMAIN="${MULLE_DOMAIN:-${PWD}/../../mulle-domain}"
 }
 
